# -*- coding: utf-8 -*-
"""FormClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTSR0rpfdNyJwrX8av0_jzisS9czTHR8

## **Install EasyOCR**
"""

!pip install easyocr

from easyocr import Reader      # Using EasyOCR for extracting text

# Load model for the English language
language_reader = Reader(["en"])

"""## **Install Pypdfium**"""

!pip install -U pypdfium2

!pip install PyPDF2

"""## **Import required packages**"""

import pypdfium2 as pdfium
import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
from io import BytesIO
import glob
import os

df = pd.DataFrame(columns = ('filename', 'formtype', 'text_content', 'label'))
df

"""## **Function to fetch the first page of all the pdf files**"""

def get_first_page_only(pdf_path):
    pages_to_keep = [0] # page numbering starts from 0
    infile = PdfReader(pdf_path, 'rb')
    output = PdfWriter()

    for i in pages_to_keep:
        p = infile.pages[i]
        output.add_page(p)

    with open('/content/drive/MyDrive/modified_sec_edgar/' + os.path.split(pdf_path)[-1], 'wb') as f:
        output.write(f)

"""## **Function to extract Text from Images**"""

def extract_text_with_easyocr(list_dict_final_images):

    image_list = [list(data.values())[0] for data in list_dict_final_images]
    image_content = []

    for index, image_bytes in enumerate(image_list):

        image = Image.open(BytesIO(image_bytes))
        raw_text = language_reader.readtext(image)
        raw_text = "\n".join([res[1] for res in raw_text])

        image_content.append(raw_text)

    return "\n".join(image_content)

"""## **Function to convert PDF to Images**"""

def convert_pdf_to_images(file_path, scale=300/72):

    pdf_file = pdfium.PdfDocument(file_path)
    page_indices = [i for i in range(len(pdf_file))]

    renderer = pdf_file.render(
        pdfium.PdfBitmap.to_pil,
        page_indices = page_indices,
        scale = scale,
    )

    list_final_images = []

    for i, image in zip(page_indices, renderer):

        image_byte_array = BytesIO()
        image.save(image_byte_array, format='jpeg', optimize=True)
        image_byte_array = image_byte_array.getvalue()
        list_final_images.append(dict({i:image_byte_array}))

    # text_with_easy_ocr = extract_text_with_easyocr(list_final_images)

    return list_final_images

"""## **Function to display the converted Images**"""

# def display_images(list_dict_final_images):

#     all_images = [list(data.values())[0] for data in list_dict_final_images]

#     for index, image_bytes in enumerate(all_images):

#         image = Image.open(BytesIO(image_bytes))
#         figure = plt.figure(figsize = (image.width / 100, image.height / 100))

#         plt.title(f"----- Page Number {index+1} -----")
#         plt.imshow(image)
#         plt.axis("off")
#         plt.show()

# Passing all the complete pdf files to fetch the first page and store in a seperate directory

pdfs = glob.glob('/content/drive/MyDrive/sec_edgar/*.pdf')
for i in pdfs:
    get_first_page_only(i)

# Populating the 'filename' column with the pdf names

pdfs = glob.glob('/content/drive/MyDrive/sec_edgar/*.pdf')
for n, file in zip(range(len(pdfs)), pdfs):
    df.at[n, 'filename'] = os.path.split(file)[-1]

# df.to_excel("SEC NLP Assignment.xlsx")

df = pd.read_csv('/content/drive/MyDrive/SEC NLP Assignment.csv')
df

# Labelling the different Form types with distinct labels

for i in range(0, 304):
    if df.at[i, 'formtype']=='Form D':
      df.at[i, 'label'] = 0
    elif df.at[i, 'formtype']=='Form 13F':
      df.at[i, 'label'] = 1
    elif df.at[i, 'formtype']=='Form X-17A-5':
      df.at[i, 'label'] = 2
    elif df.at[i, 'formtype']=='Form TA-2':
      df.at[i, 'label'] = 3
    elif df.at[i, 'formtype']=='Form 6-K':
      df.at[i, 'label'] = 4
    elif df.at[i, 'formtype']=='Form 11-K':
      df.at[i, 'label'] = 5
    elif df.at[i, 'formtype']=='Form 19B-4':
      df.at[i, 'label'] = 6
    elif df.at[i, 'formtype']=='Other':
      df.at[i, 'label'] = 7

df

"""## **Function call to extract text from all the pdf files**"""

mod_pdfs = glob.glob('/content/drive/MyDrive/modified_sec_edgar/*.pdf')
all_pdf_content = []      # list to get the pdf text content
for i in mod_pdfs:
  print(i)
  converted_image = convert_pdf_to_images(i)
  text_with_easy_ocr = extract_text_with_easyocr(converted_image)
  all_pdf_content.append(text_with_easy_ocr)

df['text_content'] = all_pdf_content       # Dataframe with all the values populated
df

df.to_csv('Final NLP dataset.csv')

df = pd.read_csv('/content/drive/MyDrive/SEC NLP Assignment.csv')

"""## **Exploratory Data Analysis (EDA)**"""

df['formtype'].value_counts()

df.shape

ax = df['formtype'].value_counts().plot(kind = 'barh', title = 'Formtype count')
ax.set_xlabel('Count')
ax.set_ylabel('Formtype')

df.groupby('formtype').describe()

df['formtype'].value_counts()

"""
---


**As we can see from above, there is a huge class
imbalance issue in the dataset with Form 13F having relatively high samples than all the other form types. This results in Overfitting of the model. Also, we can drop the Form types which are having very less samples to avoid affecting the accuracy of the model.**

---



"""

form_list = ['Form TA-2', 'Form 19B-4', 'Form 6-K', 'Form 11-K']

index_list = []

for i in form_list:
  a = list(df.index[df['formtype'] == i])
  for n in a:
    index_list.append(n)

index_list

"""**Dropping the Forms having very less samples**"""

df = df.drop(index_list)

df['formtype'].value_counts()

"""**Downsampling the Form 13F to a size equivalent to Form D and Other type**"""

df_FORMD = df[df['formtype']=='Form D']
df_FORMD.shape

df_FORM13F = df[df['formtype']=='Form 13F']
df_FORM13F.shape

df_rest = df[df['formtype'].isin(['Form X-17A-5', 'Other'])]
df_rest.shape

df_FORM13F_downsampled = df_FORM13F.sample(df_FORMD.shape[0])
df_FORM13F_downsampled.shape

df_balanced = pd.concat([df_FORM13F_downsampled, df_FORMD, df_rest])
df_balanced.shape

df_balanced['formtype'].value_counts()

!pip install swifter

try:
    import json
    import os

    import pandas as  pd
    import numpy as np
    import spacy

    import seaborn as sns
    import string

    from tqdm import tqdm
    from textblob import TextBlob

    from nltk.corpus import stopwords
    import nltk
    from nltk.stem import WordNetLemmatizer
    from nltk import word_tokenize
    import re


    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import LabelEncoder
    from sklearn.feature_extraction.text import CountVectorizer
    from sklearn.feature_extraction.text import TfidfTransformer
    from sklearn.naive_bayes import MultinomialNB
    from sklearn.pipeline import Pipeline


    from sklearn.preprocessing import FunctionTransformer
    from sklearn.base import BaseEstimator, TransformerMixin
    from sklearn.pipeline import FeatureUnion
    from sklearn.feature_extraction import DictVectorizer

    import swifter

    tqdm.pandas()
except Exception as e:
    print("Error : {} ".format(e))

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

"""## **Cleaning the extracted text**"""

stop_words_ = set(stopwords.words('english'))
wn = WordNetLemmatizer()
my_sw = ['make', 'amp',  'news','new' ,'time', 'u','s', 'photos',  'get', 'say']

def black_txt(token):
    return  token not in stop_words_ and token not in list(string.punctuation)  and len(token)>2 and token not in my_sw

def clean_txt(text):
    clean_text = []
    clean_text2 = []
    text = re.sub("'", "",text)
    text=re.sub("(\\d|\\W)+"," ",text)
    clean_text = [wn.lemmatize(word, pos="v") for word in word_tokenize(text.lower()) if black_txt(word)]
    clean_text2 = [word for word in clean_text if black_txt(word)]
    return " ".join(clean_text2)

def subj_txt(text):
    return  TextBlob(text).sentiment[1]

df_balanced['text_content'] = df_balanced['text_content'].swifter.apply(clean_txt)

"""## **Splitting the data into Train and Test sets**"""

from sklearn.model_selection import train_test_split

X = df_balanced['text_content']
y =df_balanced['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
v = dict(zip(list(y), df_balanced['formtype'].to_list()))

"""## **Creating a Pipeline including Naive Bayes Classifier for classification of Documents**"""

text_clf = Pipeline([
...     ('vect', CountVectorizer(analyzer="word", stop_words="english")),
...     ('tfidf', TfidfTransformer(use_idf=True)),
...     ('clf', MultinomialNB(alpha=.01)),
... ])

text_clf.fit(X_train.to_list(), list(y_train))

X_TEST = X_test.to_list()
Y_TEST = list(y_test)

"""## **Predicting on Test set**"""

predicted = text_clf.predict(X_TEST)

len(predicted)

c = 0
y_pred =[]
y_pred1 = []
for doc, category in zip(X_TEST, predicted):

    # if c == 2:break

    print("-"*55)
    print(doc)
    print("Predicted Label:"+ v[category])
    y_pred.append(category)
    y_pred1.append(v[category])
    print("Original Label:"+ str(Y_TEST[c]))
    print("-"*55)

    c = c + 1

print(y_pred)

"""## **Evaluation Metrics and Sample predictions**"""

np.mean(predicted == Y_TEST)

docs_new = X_TEST[12]
docs_new

predicted = text_clf.predict(list(docs_new))

v[predicted[12]]

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

table = pd.DataFrame(confusion_matrix(y_test, y_pred))

ax = sns.heatmap(table, annot=True, fmt='d', cmap='viridis')
ax.set_xlabel('Predicted labels')
ax.set_ylabel('True labels')
ax.set_title('Confusion Matrix')
ax.xaxis.set_ticklabels(['Form D', 'Form 13F', 'Form X-17A-5', 'Other'])
ax.yaxis.set_ticklabels(['Form D', 'Form 13F', 'Form X-17A-5', 'Other'])

from sklearn.metrics import accuracy_score

print(f'Accuracy Score is {accuracy_score(y_test,y_pred)}')